Public Interface iHeroUnit
  Inherits iPlayerUnit
  Property HeroName As eHeroName

  Property Roles As List(Of eRole)

  Property Goldcurve As EconomyCurve

  Property XPCurve As EconomyCurve
  Function GetCurrentGold(time As ddFrame) As Integer

  'Property PrimartyStat As Stat

  'Property BaseStrength As Double
  'Property StrenghIncrement As Double
  'Property BaseIntelligence As Double
  'Property IntellingenceIncrement As Double
  'Property BaseAgility As Double
  'Property AgilityIncrement As Double

  Property PetsOwned As List(Of PetStack)
  Property AbilityInventory As Hero_Ability_Inventory
  'Property ItemBuildSequence As Item_List
  'Property ItemBuildAndAutoGeneratedItems As Item_List
  Property ItemInventory As Hero_Item_Inventory

  Function GetBuild() As Build
  Function GetHero() As Hero
End Interface
